### ISSUE TITLE
add a react projects

### ISSUE THREAD

**Issue by Ravikumar7210** [Ravikumar7210/hacktoberfest-2k23#26]

**Comment by ayush2390** [comment]
[project-name.zip](https://github.com/Ravikumar7210/hacktoberfest-2k23/files/13175730/project-name.zip)

**Comment by Ravikumar7210** [comment]
[project-name.zip](https://github.com/Ravikumar7210/hacktoberfest-2k23/files/13175767/project-name.zip)

**Comment by Ravikumar7210** [comment]
nil
